version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: mywebsite_db
      MYSQL_USER: root
      MYSQL_PASSWORD: StrongPassword123!
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
volumes:
  mysql-data:

